import {Direction, Site} from './meteo.models';

export const SITES: Site[] = [
  {
    id: 'olhain',
    name: 'Olhain',
    lat: 50.4343,
    lon: 2.586,
    orientations: [Direction.SSO, Direction.S],
    windMin: 13,
    windMax: 23,
  },
  {
    id: 'lacomte',
    name: 'La Comté',
    lat: 50.433331,
    lon: 2.5,
    orientations: [Direction.O, Direction.ONO, Direction.NO, Direction.NNO],
    windMin: 13,
    windMax: 25,
  },
  {
    id: 'licques',
    name: 'Licques',
    lat: 50.7855,
    lon: 1.9355,
    orientations: [Direction.SSE, Direction.S, Direction.SSO],
    windMin: 13,
    windMax: 22,
  },
  {
    id: 'equihen',
    name: 'Equihen',
    lat: 50.6796,
    lon: 1.567,
    orientations: [Direction.OSO, Direction.O],
    windMin: 15,
    windMax: 30,
  },
  {
    id: 'parcdesiles',
    name: 'Parc des Iles',
    lat: 50.4014,
    lon: 2.9342,
    orientations: [Direction.SE, Direction.S],
    windMin: 13,
    windMax: 25,
  },
  {
    id: 'montsainteloi',
    name: 'Mont Saint Eloi',
    lat: 50.3311,
    lon: 2.6632,
    orientations: [Direction.NE, Direction.SO],
    windMin: 13,
    windMax: 25,
  },
  {
    id: 'zuydcoote',
    name: 'Zuydcoote',
    lat: 51.0692,
    lon: 2.4703,
    orientations: [Direction.O, Direction.NO, Direction.N],
    windMin: 15,
    windMax: 30,
  },
  {
    id: 'wissant',
    name: 'Dune de Wissant',
    lat: 50.8833,
    lon: 1.6667,
    orientations: [Direction.O, Direction.SO, Direction.NO, Direction.N, Direction.NE],
    windMin: 15,
    windMax: 30,
  },
  {
    id: 'sangatte',
    name: 'Sangatte',
    lat: 50.9412,
    lon: 1.7378,
    orientations: [Direction.NO],
    windMin: 15,
    windMax: 30,
  },
  {
    id: 'escalles',
    name: 'Escalles',
    lat: 50.9167,
    lon: 1.7167,
    orientations: [Direction.O, Direction.NO],
    windMin: 15,
    windMax: 30,
  },
  {
    id: 'frencq',
    name: 'Frencq',
    lat: 50.5605,
    lon: 1.6662,
    orientations: [Direction.NE],
    windMin: 13,
    windMax: 25,
  },
  {
    id: 'cranauxoeufs',
    name: 'Cran aux Oeufs',
    lat: 50.8472,
    lon: 1.5833,
    orientations: [Direction.SSE, Direction.S, Direction.SSO],
    windMin: 13,
    windMax: 25,
  },
  {
    id: 'lacreche',
    name: 'La Crèche',
    lat: 50.7511,
    lon: 1.5972,
    orientations: [Direction.NO, Direction.O],
    windMin: 15,
    windMax: 30,
  },
];